name: Go CI

on:
  push:
    branches: [ main ]
    tags: [ v* ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    
    - name: Initialize Git submodules
      run: |
        git submodule init
        git submodule update    

    - name: Install dependencies
      run: make deps

    - name: Run go fmt
      run: make fmt

    - name: Run go vet
      run: make vet

    - name: Run staticcheck
      run: |
        go install honnef.co/go/tools/cmd/staticcheck@latest
        staticcheck ./...

    - name: Run tests
      run: make test

    - name: Build binaries
      run: make build

    - name: Create tarball
      run: tar -czvf bin.tar.gz bin

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: binary
        path: bin.tar.gz

    - name: Upload release asset
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: bin.tar.gz
        asset_name: bin-${{ github.ref_name }}.tar.gz
        asset_content_type: application/gzip